import { AppCategory, App } from './types';

export const CATEGORIES: AppCategory[] = [
  AppCategory.Gaming,
  AppCategory.Productivity,
  AppCategory.Social,
  AppCategory.Entertainment,
  AppCategory.Education,
  AppCategory.Health,
];

export const APPS: App[] = [
  {
    id: 1,
    name: 'مغامرات الفضاء',
    category: AppCategory.Gaming,
    rating: 4.8,
    downloads: '1.2 مليون',
    iconUrl: 'https://picsum.photos/seed/space/200',
    description: 'استكشف المجرة في لعبة المغامرات المثيرة هذه.',
    downloadUrls: ['#'],
  },
  {
    id: 2,
    name: 'مساعد التركيز',
    category: AppCategory.Productivity,
    rating: 4.5,
    downloads: '500 ألف',
    iconUrl: 'https://picsum.photos/seed/focus/200',
    description: 'عزز إنتاجيتك مع تقنيات إدارة الوقت المتقدمة.',
    downloadUrls: ['#'],
  },
  {
    id: 3,
    name: 'كونكت بلس',
    category: AppCategory.Social,
    rating: 4.6,
    downloads: '3 مليون',
    iconUrl: 'https://picsum.photos/seed/connect/200',
    description: 'تواصل مع أصدقائك وعائلتك بسهولة وأمان.',
    downloadUrls: ['#'],
  },
  {
    id: 4,
    name: 'سينما تايم',
    category: AppCategory.Entertainment,
    rating: 4.9,
    downloads: '5 مليون',
    iconUrl: 'https://picsum.photos/seed/cinema/200',
    description: 'شاهد أحدث الأفلام والمسلسلات بجودة عالية.',
    downloadUrls: ['#'],
  },
  {
    id: 5,
    name: 'أكاديمية المعرفة',
    category: AppCategory.Education,
    rating: 4.7,
    downloads: '800 ألف',
    iconUrl: 'https://picsum.photos/seed/academy/200',
    description: 'تعلم مهارات جديدة مع آلاف الدورات المتاحة.',
    downloadUrls: ['#'],
  },
  {
    id: 6,
    name: 'فتنس برو',
    category: AppCategory.Health,
    rating: 4.8,
    downloads: '1.5 مليون',
    iconUrl: 'https://picsum.photos/seed/fitness/200',
    description: 'رفيقك المثالي لتحقيق أهدافك الصحية واللياقة البدنية.',
    downloadUrls: ['#'],
  },
  {
    id: 7,
    name: 'سباق الصحراء',
    category: AppCategory.Gaming,
    rating: 4.4,
    downloads: '950 ألف',
    iconUrl: 'https://picsum.photos/seed/desert/200',
    description: 'تسابق عبر الكثبان الرملية في لعبة سباق سيارات مثيرة.',
    downloadUrls: ['#'],
  },
  {
    id: 8,
    name: 'نوت بوك الذكي',
    category: AppCategory.Productivity,
    rating: 4.6,
    downloads: '1.1 مليون',
    iconUrl: 'https://picsum.photos/seed/notebook/200',
    description: 'دون ملاحظاتك وأفكارك بذكاء وسرعة.',
    downloadUrls: ['#'],
  },
  {
    id: 9,
    name: 'شير مومنتس',
    category: AppCategory.Social,
    rating: 4.3,
    downloads: '2.2 مليون',
    iconUrl: 'https://picsum.photos/seed/moments/200',
    description: 'شارك لحظاتك السعيدة مع العالم.',
    downloadUrls: ['#'],
  },
   {
    id: 10,
    name: 'مطبخي',
    category: AppCategory.Education,
    rating: 4.9,
    downloads: '2.5 مليون',
    iconUrl: 'https://picsum.photos/seed/kitchen/200',
    description: 'تعلم وصفات جديدة من جميع أنحاء العالم.',
    downloadUrls: ['#'],
  },
  {
    id: 11,
    name: 'ميوزك ويف',
    category: AppCategory.Entertainment,
    rating: 4.7,
    downloads: '4.1 مليون',
    iconUrl: 'https://picsum.photos/seed/music/200',
    description: 'استمع إلى ملايين الأغاني والبودكاست بدون حدود.',
    downloadUrls: ['#'],
  },
  {
    id: 12,
    name: 'تأمل هادئ',
    category: AppCategory.Health,
    rating: 4.9,
    downloads: '900 ألف',
    iconUrl: 'https://picsum.photos/seed/meditate/200',
    description: 'ابحث عن السلام الداخلي مع جلسات تأمل موجهة.',
    downloadUrls: ['#'],
  }
];